# Generated by Django 5.1.6 on 2025-03-04 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopdetails',
            name='email',
        ),
        migrations.AlterField(
            model_name='shopdetails',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
