# Generated by Django 5.1.6 on 2025-03-04 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_shopdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetails',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
