# Generated by Django 5.1.6 on 2025-03-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shopdetails_gstin_alter_shopdetails_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='bw_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per B&W print (in INR)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='shopdetails',
            name='color_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per Color print (in INR)', max_digits=5, null=True),
        ),
    ]
